# Generated by Django 6.0.5 on 2026-05-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(db_column='ruta_id', on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
