# Generated by Django 6.0.5 on 2026-06-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numero_documento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', max_length=20)),
                ('foto_documento', models.ImageField(blank=True, null=True, upload_to='clientes/documentos/')),
                ('ruta', models.ForeignKey(blank=True, db_column='ruta_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta')),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
