# Generated by Django 6.0.5 on 2026-06-13 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_principal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='InventarioRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('ruta', models.ForeignKey(db_column='ruta_id', on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'db_table': 'inventario_ruta',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(db_column='ruta_id', on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta')),
            ],
            options={
                'db_table': 'transferenciaInventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('transferencia', models.ForeignKey(db_column='transferencia_id', on_delete=django.db.models.deletion.CASCADE, to='inventario.transferenciainventario')),
            ],
            options={
                'db_table': 'detalle_transferencias',
            },
        ),
    ]
