# Generated by Django 6.0.5 on 2026-06-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventarioruta',
            unique_together=set(),
        ),
    ]
