# Generated by Django 6.0.5 on 2026-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioruta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
