# Generated by Django 6.0.5 on 2026-06-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventarioruta_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciainventario',
            options={'ordering': ['-fecha']},
        ),
    ]
