# Generated by Django 6.0.5 on 2026-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobro_observacion_alter_cobro_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
    ]
