# Generated by Django 6.0.5 on 2026-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='frecuencia_cobro',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('COMPLETO', 'Pago Completo')], default='SEMANAL', max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='proximo_cobro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
