# Generated by Django 6.0.5 on 2026-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_frecuencia_cobro_venta_proximo_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
